### ISSUE TITLE
Make EDIFF scale with the number of atoms

### ISSUE THREAD

**Issue by zhubonan** [kavanase/doped#2]
For large supercell calculation, the EDIFF value might be a bit too small?

https://github.com/kavanase/doped/blob/98ccf65d02f440983d3abf6fef8b5391aa6c876a/doped/vasp_input.py#L240

If say the cell has 100 atoms, this essentially 5e-8 eV per atom, which seems a bit too tight from the initial relaxation? 

It may be better to make it scale with the number of atoms. I personally often use 1e-5 per atom to get reasonably accurate forces.

**Comment by kavanase** [comment]
Thanks for the suggestion @zhubonan!

I understand this from the perspective of a full structure optimisation for a cell with a large number of atoms, but for defect supercells, the atomic forces should be primarily localised around the defect centre right? 
So the `EDIFF` required to get accurate forces should be relatively independent of the cell size?

**Comment by kavanase** [comment]
Either way, I do agree the default `INCAR` convergence criteria for `vasp_gam_files` is too strict, so at the very least, I'll change `EDIFF` to 1e-5 and `EDIFFG` to -0.01.

**Comment by zhubonan** [comment]
I think constant EDIFF per atom should mean a similar level of quality for wave function/charge density, hence similar force accuracy. For example, imaging making a supercell of a well-converged system by simply repeating the wave function and charge density in one direction - now the TOTEN is doubled and so does EDIFF, but the force acting on each is the same.

**Comment by kavanase** [comment]
Ah ok I see your point. Will implement with an upper limit `EDIFF` of 1e-4 (if you want to report defect energies converged to meV energies)

**Comment by zhubonan** [comment]
hmm, I see that is also a good point - for larger cells the errors would add up in the total energy. Makes sense to have an upper bound as well.

**Comment by kavanase** [comment]
Implemented in 784d965, thanks @zhubonan!
